#!/bin/bash

directory=$1
moduleName=$0

chmod +x Generatus.sh

echo "⚡️Generatus © Powered by Ryasnoy Oleg⚡️"

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/Templates"

function generateTemplatesFiles () {
  echo "Enter module name:"
  read moduleName
# /Users/oleg/Documents/Generatus/
  echo "Generating in $directory"
  cd $directory && mkdir $moduleName && cd $moduleName
  cp -R $DIR/*.swift $directory/$moduleName
  for i in *.swift ; do
  mv $i `echo "$i"|awk -F'.' '{print "'$moduleName'"$1"."$2}'`
  sed -i '' 's/#mdlnm/'$moduleName'/g' *.swift
done

}

function enterDirectory () {
  echo "Enter directory path:"
  read directory
  if [[ -d "$directory" ]]; then
  generateTemplatesFiles
  else
    echo "Invalid directory. Enter valid directory:"
    enterDirectory
  fi
}

function askAboutInteractor () {
  read -r -p "Do you want create Interactor(Use Case)? [y/N] " response
case "$response" in
    [yY][eE][sS]|[yY])
        generateInteractorFile
        ;;
    *)
    echo "⚡️Thank you for using Generatus⚡️"  ;;
esac
}

function generateInteractorFile () {
  echo "Enter Interactor (Use Case) name:"
  read interactor
  touch $interactor"Interactor".swift
  echo "// ⚡️Generated by Generatus⚡️
//
// $moduleName"Interactor".swift
//
// **************************
//  Powered by Ryasnoy Oleg
// **************************" >> $interactor"Interactor".swift
  echo "$interactor"Interactor".swift created"
  askAboutInteractor
}

enterDirectory
askAboutInteractor

exit 0
