// ⚡️Generated by Generatus⚡️
// 
// #mdlnmRouter.swift
//
// **************************
//  Powered by Ryasnoy Oleg
// **************************

import Foundation

class #mdlnmRouterImplementation {

  /// View object
  fileprivate weak var view: #mdlnmViewController?
  
  init(view: #mdlnmViewController) {
    self.view = view
  }

}

//MARK: - #mdlnmRouter

extension #mdlnmRouterImplementation: #mdlnmRouter {
  
}
